#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PasswordGenerator.Android.Resource", IsApplication=true)]

namespace PasswordGenerator.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::PasswordGenerator.Android.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::PasswordGenerator.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int black = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Collapse = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Expand = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rect_frame_gray = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060036
			public const int btnCopy = 2131099702;
			
			// aapt resource value: 0x7f060006
			public const int btnGenerate = 2131099654;
			
			// aapt resource value: 0x7f060032
			public const int btnSubmit = 2131099698;
			
			// aapt resource value: 0x7f060011
			public const int cbLower = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int cbNum = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int cbSignals = 2131099675;
			
			// aapt resource value: 0x7f06000c
			public const int cbUpper = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int imgOptions = 2131099656;
			
			// aapt resource value: 0x7f06002c
			public const int linearLayout8 = 2131099692;
			
			// aapt resource value: 0x7f06002f
			public const int linearLayout9 = 2131099695;
			
			// aapt resource value: 0x7f060000
			public const int lyt1 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int lyt2 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int lytOptionExpand = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int lytOptions = 2131099658;
			
			// aapt resource value: 0x7f060033
			public const int lytResult = 2131099699;
			
			// aapt resource value: 0x7f060012
			public const int rGroupLower = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int rGroupNum = 2131099671;
			
			// aapt resource value: 0x7f06001c
			public const int rGroupSignals = 2131099676;
			
			// aapt resource value: 0x7f06000d
			public const int rGroupUpper = 2131099661;
			
			// aapt resource value: 0x7f060014
			public const int rbLower_Must = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int rbLower_Optional = 2131099667;
			
			// aapt resource value: 0x7f060019
			public const int rbNum_Must = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int rbNum_Optional = 2131099672;
			
			// aapt resource value: 0x7f06001e
			public const int rbSignals_Must = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int rbSignals_Optional = 2131099677;
			
			// aapt resource value: 0x7f06000f
			public const int rbUpper_Must = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int rbUpper_Optional = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int rlytLower = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int rlytNumber = 2131099669;
			
			// aapt resource value: 0x7f06001a
			public const int rlytSignals = 2131099674;
			
			// aapt resource value: 0x7f06000b
			public const int rlytUpper = 2131099659;
			
			// aapt resource value: 0x7f060020
			public const int tbtn1 = 2131099680;
			
			// aapt resource value: 0x7f060029
			public const int tbtn10 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int tbtn11 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int tbtn12 = 2131099691;
			
			// aapt resource value: 0x7f060021
			public const int tbtn2 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int tbtn3 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int tbtn4 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int tbtn5 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int tbtn6 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int tbtn7 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int tbtn8 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int tbtn9 = 2131099688;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int textView3 = 2131099652;
			
			// aapt resource value: 0x7f060034
			public const int textView4 = 2131099700;
			
			// aapt resource value: 0x7f060009
			public const int textView6 = 2131099657;
			
			// aapt resource value: 0x7f06002d
			public const int textView7 = 2131099693;
			
			// aapt resource value: 0x7f060030
			public const int textView9 = 2131099696;
			
			// aapt resource value: 0x7f06001f
			public const int tlytSignals = 2131099679;
			
			// aapt resource value: 0x7f060035
			public const int tvResult = 2131099701;
			
			// aapt resource value: 0x7f06002e
			public const int tvSimpleKey = 2131099694;
			
			// aapt resource value: 0x7f060002
			public const int txtKeywords = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int txtLength = 2131099653;
			
			// aapt resource value: 0x7f060031
			public const int txtSimpleKey = 2131099697;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int AtSignal = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int QuestionSignal = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
