#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PasswordGenerator.Android.Resource", IsApplication=true)]

namespace PasswordGenerator.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::PasswordGenerator.Android.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::PasswordGenerator.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int black = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Collapse = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Expand = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int button1 = 2131099654;
			
			// aapt resource value: 0x7f060016
			public const int button2 = 2131099670;
			
			// aapt resource value: 0x7f06000c
			public const int checkBox1 = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int checkBox2 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int checkBox3 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int checkBox4 = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int editText1 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int imageView1 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout6 = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int lyt1 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int lyt2 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int lytOptionExpand = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int lytOptions = 2131099658;
			
			// aapt resource value: 0x7f060013
			public const int lytResult = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int radioButton1 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int radioButton2 = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int radioGroup1 = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int textView3 = 2131099652;
			
			// aapt resource value: 0x7f060014
			public const int textView4 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int textView5 = 2131099669;
			
			// aapt resource value: 0x7f060009
			public const int textView6 = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
